// src/app/sections/awards/awards.component.ts
import { Component } from '@angular/core';
import { Award } from 'src/app/models/award.type';
import { NgFor, NgClass, NgIf, NgOptimizedImage } from '@angular/common';
import gsap from 'gsap';

@Component({
  selector: 'app-awards',
  templateUrl: './awards.component.html',
  styleUrls: ['./awards.component.scss'],
  standalone: true,
  imports: [NgFor, NgClass, NgIf]
})
export class AwardsComponent {


  awards: Award[] = [
    {
      title: "1st place at ROBO DAYS'23, competition hosted by Technical University Sofia",
      description: "Working together with a talented classmate, our team managed to clinch the top spot in the software project category, leaving other teams behind.",
      date: "04/2023",
      location: "Sofia",
      imageUrl: "../../../assets/robodays.webp",
    },
    {
      title: "1st place at BurgasBlueS 2023, hackathon hosted by University prof. dr.Asen Zlatarov ",
      description: "Me and my friend formed a successful team that placed at first position in the junior project category, surpassing numerous competing teamsemerging as the ultimate winners.",
      date: "06/2023",
      location: "Burgas",
      imageUrl: "../../../assets/burgasblues.webp",
    },
    {
      title: " Secured 7th place at the National Competition of IT, comprising regional and national",
      description: "In the regional phase, I achieved an impressive score of 93 out of 100. Moving on to the national phase, I performed exceptionally well, securing the 3rd place out of 30 participants in the test with a score of 89 out of 100. Additionally, in the presentation component of the national phase, I attained a commendable score of 77 out of 100.",
      date: "04/2023",
      location: "Shumen",
      imageUrl: "../../../assets/noit.png",
    },
    {
      title: "Diploma Vyarnata posoka",
      description: "I was honored with the prestigious 'Vyarnata Posoka' diploma, awarded for my exceptional performance in the National Olympiad in Information Technology, where I secured an impressive 7th place in the 8-10th class age category.",
      date: "06/2021",
      location: "Burgas",
      imageUrl: "../../../assets/vyarnataposoka.webp",
    },
    {
      title: "2nd place at 6-th Regional IT Competition",
      description: "I attained the '2nd place' at the 6th Regional IT Competition in Burgas. The competition consisted of both a theoretical and practical section. I achieved a score of 98 out of 100.",
      date: "06/2021",
      location: "Burgas",
      imageUrl: undefined,
    },


  ]



  ngAfterContentInit(): void {
    //Called after ngOnInit when the component's or directive's content has been initialized.
    //Add 'implements AfterContentInit' to the class.


    const documents = [
      document.querySelector("#awardTitle"),
      document.querySelector("#awardWrapper"),
    ];

    let tl = gsap.timeline({
      scrollTrigger: {
        trigger: "#awardWrapper",
        start: "-300 center",
        end: "350 top",
        scrub: 1,
        markers: true,
      },


    });

    tl.fromTo("#awardTitle", { opacity: 0, y: 300 }, { opacity: 1, y: 0, duration: 1 }, 0);
    tl.fromTo(".awards", { opacity: 0, y: 300 }, { opacity: 1, y: 0, duration: 1 }, 0);

    const awards = gsap.utils.toArray('.award');

    function fadeIn(targets: HTMLElement[]) {
      targets.forEach((element, i) => {

        gsap.fromTo(element, {
          x: i % 2 == 0 ? -1000 : 1000,
          opacity: 0,
        }, {
          opacity: 1,
          x: 0,
          duration: 1,

          ease: "power2.out",

        });
      });
    }

    let observer = new IntersectionObserver(function (entries, self) {
      let targets = entries.map(entry => {

        if (entry.isIntersecting) {
          self.unobserve(entry.target);
          return entry.target;
        }

        return null;
      });

      // Call our animation function
      fadeIn(targets as HTMLElement[]);
    }, { threshold: 0.1 });

    document.querySelectorAll('.award').forEach(box => {
      observer.observe(box);
    });
  }


}

<div class="wave">

</div>

<div class="wrapper">


  <h1 class="title-text">My awards</h1>

  <div class="awards">

    <div class="award" [ngClass]="{'reversed': (i + 1) % 2 == 0}" *ngFor="let item of awards; let i=index">
      <div class="info" [ngClass]="{'solo': item.imageUrl}">
        <div class="location-time" [ngClass]="{'location-reversed': (i) % 2 ==0}">
          <h4 id="location">{{item.location}}</h4>
          <h4>{{item.date}}</h4>
        </div>
        <div class="txt-layout" [ngClass]="{'reversed': (i ) % 2 == 0}">
          <h1>{{item.title}}</h1>
          <div class="divider">

          </div>
          <p>{{item.description}}</p>
        </div>
      </div>
      <img *ngIf="item.imageUrl" alt="award image" src="{{item.imageUrl}}" clickable>
    </div>
    <div class="award">
      <div class="info">
        <div class="location-time location-reversed">
          <h4 id="location">Burgas and Shumen</h4>
          <h4>04/2023</h4>
        </div>
        <div class="txt-layout txt-reverse">
          <div>
            <h1>7th place at National Competition of IT</h1>
          </div>
          <div class="divider"></div>
          <div>
            <p>
              Secured 7th place at the National Competition of IT, comprising regional
              and national

              04/2023

              phases.
            </p>
            <ul>
              <li>Regional Phase: Attained a score of 93 out of 100.</li>
              <li>National Phase:
                <ul>
                  <li>Test: Earned a score of 89 out of 100 (3rd place out of 30)</li>
                  <li>Presentation: Achieved a score of 77 out of 100</li>
                </ul>
              </li>
            </ul>
          </div>


        </div>
      </div>
      <img src="../../../assets/noit.png" clickable>
    </div>
    <div class="award reversed">
      <div class="info">
        <div class="location-time">
          <h4 id="location">Online</h4>
          <h4>02/2023</h4>
        </div>
        <div class="txt-layout ">
          <h1>2nd place at SoftUniada 2023</h1>
          <div class="divider"></div>
          <p>During SoftUniada 2023, I achieved 2nd place in the junior project category
            with my outstanding project EducateIO. I demonstrated innovative skills
            and surpassed numerous competitors, earning recognition for our
            exceptional work.</p>

        </div>
      </div>
      <iframe height="315" src="https://www.youtube.com/embed/5OdUHyuf-7A?start=834" title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
    </div>
  </div>

</div>
<div class="wave wave-out">

</div>

// src/lib/sections/Awards.svelte
<script lang="ts">
	import AwardCard from '$lib/components/AwardCard.svelte';
	import type { Award } from '$lib/models/award.type';
	import { onMount } from 'svelte';

	import gsap from 'gsap';

	let awards: Award[] = [
		{
			title: "1st place at ROBO DAYS'23, competition hosted by Technical University Sofia",
			description:
				'Working together with a talented classmate, our team managed to clinch the top spot in the software project category, leaving other teams behind.',
			date: '04/2023',
			location: 'Sofia',
			imageUrl: '/robodays.webp'
		},
		{
			title:
				'1st place at BurgasBlueS 2023, hackathon hosted by University prof. dr.Asen Zlatarov ',
			description:
				'Me and my friend formed a successful team that placed at first position in the junior project category, surpassing numerous competing teams emerging as the ultimate winners.',
			date: '06/2023',
			location: 'Burgas',
			imageUrl: '/burgasblues.webp'
		},
		{
			title:
				' Secured 7th place at the National Competition of IT, comprising regional and national',
			description:
				'In the regional phase, I achieved an impressive score of 93 out of 100. Moving on to the national phase, I performed exceptionally well, securing the 3rd place out of 30 participants in the test with a score of 89 out of 100. Additionally, in the presentation component of the national phase, I attained a commendable score of 77 out of 100.',
			date: '04/2023',
			location: 'Shumen',
			imageUrl: '/noit.png'
		},
		{
			title: 'Diploma Vyarnata posoka',
			description:
				"I was honored with the prestigious 'Vyarnata Posoka' diploma, awarded for my exceptional performance in the National Olympiad in Information Technology, where I secured an impressive 7th place in the 8-10th class age category.",
			date: '06/2021',
			location: 'Burgas',
			imageUrl: '/vyarnataposoka.webp'
		},
		{
			title: '2nd place at 6-th Regional IT Competition',
			description:
				"I attained the '2nd place' at the 6th Regional IT Competition in Burgas. The competition consisted of both a theoretical and practical section. I achieved a score of 98 out of 100.",
			date: '06/2021',
			location: 'Burgas',
			imageUrl: undefined
		}
	];

	let wrapper: HTMLElement;
	let title: HTMLElement;

	onMount(() => {
		let tl = gsap.timeline({
			scrollTrigger: {
				trigger: wrapper,
				start: 'top center',
				end: '+=300',
				scrub: 1,
				markers: true
			}
		});

		tl.fromTo(title, { opacity: 0, duration: 1, y: 300 }, { opacity: 1, duration: 1, y: 0 }, 0);
	});
</script>

<div class="wrapper" bind:this={wrapper}>
	<h1 class="title-text" bind:this={title}>Achievements</h1>

	<div class="awards">
		{#each awards as award, i}
			<div class="ach">
				<AwardCard {award} reversed={(i + 1) % 2 == 0} />
			</div>
		{/each}
		<!-- <div class="ach" *ngFor="let item of awards; let i=index">
			<app-award-card [award]="item" [reversed]="(i+1) % 2 == 0" />
		</div> -->
	</div>
</div>

<style lang="scss">
	.awards {
		display: flex;
		flex-direction: column;
		align-items: center;

		overflow: hidden;
	}

	.ach {
		margin-block: 5rem;
	}

	@media (max-width: 1100px) {
		.awards {
			width: 100%;
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			display: flex;
		}
	}
</style>
