// src/app/components/award-card/award-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Award } from 'src/app/models/award.type';

import gsap from 'gsap';

@Component({
  selector: 'app-award-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './award-card.component.html',
  styleUrls: ['./award-card.component.scss']
})
export class AwardCardComponent {
  @Input() award: Award | undefined;
  @Input() reversed: boolean = false;

  name: string = "";

  constructor() {

    setTimeout(() => {
      this.name = this.award?.description.substring(0, 15).replace(/\s/g, '') ?? "kys";
      console.log(this.name);
    }, 0);


  }

  ngOnInit(): void {
    //Called after the constructor, initializing input properties, and the first call to ngOnChanges.
    //Add 'implements OnInit' to the class.

    setTimeout(() => {
      let tl = gsap.timeline({
        scrollTrigger: {
          trigger: `#${this.name}`,
          start: "-300 center",
          end: "center center",
          markers: true,
          scrub: 1,
        },
      });

      tl.fromTo(`#content-${this.name}`, { opacity: 0, x: this.reversed ? 500 : -500 }, { opacity: 1, x: 0, duration: 1, ease: "power2.out" }, 0);
      if (this.award?.imageUrl) {

        tl.fromTo(`#img-${this.name}`, { opacity: 0, x: this.reversed ? -500 : 500 }, { opacity: 1, x: 0, duration: 1, ease: "power2.out" }, 0);
      }
    }, 0)
  }
}

<div class="award" id="{{name}}" [ngClass]="{'reversed': reversed}">
  <div class="txt" id="content-{{name}}">
    <div>
      <h1 class="title">{{award!.title}}</h1>
      <p>{{award!.description}}</p>
    </div>

    <div class="location">
      <h4>{{award!.location}}</h4>
      <h4>{{award!.date}}</h4>
    </div>
  </div>
  <div class="img" *ngIf="award!.imageUrl">
    <img id="img-{{name}}" alt="award image" src="{{award!.imageUrl}}" loading="lazy">
  </div>
</div>

// src/lib/components/AwardCard.svelte
<script lang="ts">
	import type { Award } from '$lib/models/award.type';
	import { onMount } from 'svelte';

	export let award: Award;
	export let reversed: boolean = false;

	let wrapper: HTMLElement;
	let content: HTMLElement;
	let image: HTMLElement;

	onMount(() => {
		let tl = gsap.timeline({
			scrollTrigger: {
				trigger: wrapper,
				start: '-300 center',
				end: 'center center',
				markers: false,
				scrub: 1
			}
		});

		tl.fromTo(
			content,
			{ opacity: 0, x: reversed ? 500 : -500 },
			{ opacity: 1, x: 0, duration: 1, ease: 'power2.out' },
			0
		);
		if (image) {
			tl.fromTo(
				image,
				{ opacity: 0, x: reversed ? -500 : 500 },
				{ opacity: 1, x: 0, duration: 1, ease: 'power2.out' },
				0
			);
		}
	});
</script>

<div class="award" bind:this={wrapper} class:reversed>
	<div class="txt" bind:this={content}>
		<div>
			<h1 class="title">{award.title}</h1>
			<p>{award.description}</p>
		</div>

		<div class="location">
			<h4>{award.location}</h4>
			<h5>{award.date}</h5>
		</div>
	</div>
	{#if award.imageUrl}
		<div class="img">
			<img alt="award" src={award.imageUrl} bind:this={image} />
		</div>
	{/if}
</div>

<style lang="scss">
	.award {
		display: flex;
		justify-content: center;
		align-items: center;
	}

	.txt {
		flex: 2;
		margin-inline: 3rem;
		text-align: center;

		.title {
			margin: 0;
			padding-bottom: 2%;
			border-bottom: 2px solid white;
			margin-inline: auto !important;
		}

		p {
			font-weight: 400;
			letter-spacing: 1.5px;
			font-size: 1.5rem;
			line-height: 1.5;
		}
	}

	.location {
		margin-top: 2rem;

		h4,
		h5 {
			margin: 0;
		}
	}

	.reversed {
		flex-direction: row-reverse;
	}

	.img {
		flex: 1;
		margin-inline: 3rem;
	}

	img {
		width: 100%;
		height: auto;
		border-radius: 20px;
		transition: all 600ms cubic-bezier(0.175, 0.885, 0.32, 1.275);
		box-shadow: 0px 20px 40px #381e72;

		&:hover {
			scale: 1.05 !important;
			box-shadow: 0px 20px 40px #381e72;
			border-radius: 50px;
		}
	}
</style>
